### PR TITLE
Support all type files that clang-format can format

### PR DESCRIPTION
**Pull request by KindDragon**
A tool to format C/C++/Java/JavaScript/JSON/Objective-C/Protobuf/C# code.
https://clang.llvm.org/docs/ClangFormat.html

### CODE REVIEW

**Review by asottile — APPROVED** [review]

**Comment by henryiii** [comment]
This causes clang-format to break if I have json files and don't have json config in my clang-format file (probably because I think clang-format is the wrong tool for formatting a json file; I might not even want whitespace injected). The original hook intentionally only supported the files clang can compile: C, C++, CUDA, etc., Clang can't compile json (what would that mean?) and there are other formatters for those, so I thought those should be opt-in. I described the reasoning behind this choice in https://github.com/ssciwr/clang-format-hook/pull/7. It also cause breakage if MatLab files are present, since they use `.m`, just like Objective-C (which is a horrible file extension).

Following upstream support exactly is not unreasonable either, though often a more inconvenient / surprising default, IMO. I am fine with change, if I preferred the old one and now have several breaking repositories on Monday's pre-commit update. 

If anyone needs it, my current solution is to now add `exclude: \.json$` when using it; another idea would be to just always override this when using the hook. CC @dokempf and @bdice as potentially affected too.

**Comment by Skylion007** [comment]
CUDA and C# etc should also be fine. It's the Java / Javascript / JSON etc that is breaking it. I think we should support the most common usage (formatting of C-family code) and allow users to override the types_or as appropriate.

**Comment by KindDragon** [comment]
@asottile I have no respect for the best way to proceed. With what logic do you add pre-commit-mirror? How about adding a separate `clang-format-cpp` id?

**Pull request merged**
