### PR TITLE
Add support for java files

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by asottile** [comment]
this file is generated

**Comment by m-kuhn** [comment]
I'm currently overwriting this in the local `.pre-commit-config.yaml` file. Happy to upstream something if this is desired.
Please let me know if I can follow up with a different patch (where?) or if this is undesired.

**Comment by asottile** [comment]
there's only ~10 files here -- try poking around, or looking at other PRs

**Comment by m-kuhn** [comment]
Thank you for the pointer

followup here https://github.com/pre-commit/mirrors-clang-format/pull/6

**Pull request closed without merging**
