### PR TITLE
feat: Update pre-commit-mirror command with additional file type 'metal'

### PR DESCRIPTION
**Pull request by NripeshN**

### CODE REVIEW

**Comment by asottile** [comment]
last time we added another type here I got about 30 issues for people complaining about it not being available in `identify`

I'm going to wait a month before merging this just to reduce the number of emails I'll inevitably get

**Comment by NripeshN** [comment]
> last time we added another type here I got about 30 issues for people complaining about it not being available in `identify`
> 
> I'm going to wait a month before merging this just to reduce the number of emails I'll inevitably get

I tried running this hook using the commits `sha` and you are right, the `metal` files were not being formatted. Do you know how we can add support to this repo?

**Comment by asottile** [comment]
you can override `types_or` locally until then

**Comment by NripeshN** [comment]
> you can override `types_or` locally until then

How do I do that?

**Comment by asottile** [comment]
what have you tried? have you read the docs?

**Comment by NripeshN** [comment]
> last time we added another type here I got about 30 issues for people complaining about it not being available in `identify`
> 
> I'm going to wait a month before merging this just to reduce the number of emails I'll inevitably get

Hey @asottile 
Could we take a look at this again?

**Comment by asottile** [comment]
sure wcgw

**Pull request merged**
