### PR TITLE
Add git-clang-format hook for 

### PR DESCRIPTION
**Pull request by tgross35**
This would be a useful addition, allowing large projects to bring their codebase into compliance without large diffs.

### CODE REVIEW

**Comment by asottile** [comment]
this file is generated

**Comment by tgross35** [comment]
@asottile would a similar change be accepted against the GH action workflow? Minimal overhead to add in the same repo since clang-format-wheel already ships with git-clang-format and clang-format-diff

On the subject, do hooks get the files as they exists in --to-ref when specified? Or do they get the files as they exist in the directory. Looks like it may be the latter based on source but I'm likely missing something.

**Comment by asottile** [comment]
it wouldn't work as written anyway. there's no shell involved to interpolate that value

plus I recommend always doing it in one go rather than potentially polluting every change with unrelated changes https://github.com/readme/guides/code-review

**Comment by tgross35** [comment]
I realized it wouldn’t, which I intended to discuss in the draft PR here. Regarding pollution, I would have assumed squash & merge is acceptable, otherwise I would have offered to rebase before merge.

Ok, back to the main issue. Guess this would need need a helper script. [clang-format-wheel](https://github.com/ssciwr/clang-format-wheel) doesn’t have anything to do with hooks so doesn’t seem like it belongs there. My own fork seems like a waste for a small 80-line interface wrapper. Where does it belong? Alternatively, where is a better place to discuss this?

**Comment by asottile** [comment]
no not this PR, doing incremental formatting is problematic in general

you also don't _need_ it to be an external script, you could `entry: bash -c '...' --` or if it's in just one repo you could keep your own `./scripts/whatever` and override `entry` with that

**Comment by tgross35** [comment]
Ah, thank you for the clarification. Normally I agree but the main use case is numpy, large unformatted codebase and the team thought running autoformat on the whole thing would be too disruptive to open PRs, and disliked the huge diff it would create in the middle of everything. So, incremental it is, I know numpy/scipy can’t be the only big codebase with that problem.

Will look into what you suggested, thanks. If I get it working I’ll just submit a docs pr against the original wheels repo.

**Comment by asottile** [comment]
I've tried this against 5MLOC+ codebases, incremental is kinda a disaster -- but if you believe you know better then by all means.  it's usually best to pull off the bandaid once, mark the commit as an ignored revision, and continue on into the future

**Comment by tgross35** [comment]
I certainly don’t know better, but also not up to me. I plan to get something working now so I can at least contribute with my mind at ease, then bring up the total reformat in a year or so.

Thanks for all the help!

**Pull request closed without merging**
